apiVersion: v1
kind: Pod
metadata:
  name: log-debugging-pod
  labels:
    app: log-debug
spec:
  containers:
  - name: app-container
    image: nginx
    # Add a volume mount for log files
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx
  # Add a sidecar container for log analysis
  - name: log-analyzer
    image: busybox
    command: ["sh", "-c", "tail -f /var/log/nginx/error.log"]
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx
  volumes:
  - name: log-volume
    emptyDir: {}
