apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: troubleshooting
spec:
  selector:
    app: frontend  # Fixed: was app: front-end with incorrect label
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
