apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  namespace: troubleshooting
spec:
  containers:
  - name: nginx
    image: nginx:latest  # Fixed: was nginx:latst with a typo
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "200m"
